ssh_master_pem: ENC[AES256_GCM,data:VQyt3UGKNMPkAgSVuMJqpA/+ooNpM3p4Tml7+MzH/KMy95DnCIZ3v/IuOdYyuKbqfuSoHh51W7qtQkfcYyrVVojN4nUrjvayoLm++O455Zpzto/RcrRWMRVXSV3l6A7K1uIySdQWM2msWOW/uqMc2srXUyWPh1BRn17ZJ5RwX1lYwHyXd89azNQ3plcADJi2SAhAA3zv732DM1YT1qvNX0dbMMHGWKij7RyY9fFpeBYAfo6AsmuTM6rEOs69HH9jzBW+b8QwRgPrprDnWYrV0P6GvANpauincOkPdaFtNd5r5sR4FBp75mn3KqyjeAPVdHpJB6qj5GuAh//9t/ppatnVizwZWlIvrlSOPXZZm4xbL4VmzrTk4pbGFkw0I+XsXBQDZ9S6iLjEViZMdY9GpyUVJGB93zCfNeO8cvF63VkSHxbGdqVppwoIEZkY6kugUPQb7hjYwcuHbqdCu2r/Y53SVJWtLs68KR4nJU0pV67ZW1rjGP6uVKRMrTEiDlNFy9YZxrGS2f/UYoL3eyiZXGh59kZkVdj1YHs7,iv:6oIoNCpWCDH8DpHDU87bf4Vn/vrB/wUNr6viPJJ16sU=,tag:VjXvE5bhx0sSO5BsUDzpWg==,type:str]
ssh_master_pub: ENC[AES256_GCM,data:3Nyu7ffHNZQRF3bGfN8TmaqR0zsKVXkkqc0Wb0piobxrwzav0mF5mKgJDWexRZCBVPIdBtRtTCpMQmL5r2wqWVpg5OmzD5UTTm+pQZzJGOGi4PKNahgssCJbpqz02UxwYxjpIR2K,iv:So576zLqP2jv2HIpPfaIEbIUxbI4LReCIOfg5S2Cs3k=,tag:NMbwdr531aR4eH5dUd2kLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ckghl2xua7qgun5xvz7l4h9g4rd8u09azxndurv7x3en6qq74aqh55227
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTmd4SzFKOUhxY3RBVFpS
            NUFJbzJLT0FmMG4xNEZRNFloOTl2c0R6Mkh3CklrSU1scU04Z0FZeDl3aThPS3JT
            WS94Yk1MOFA5VU9jTDZBZk1udjAxNDAKLS0tIDBWaDZSais3Z3U2clpyWEtxL2hh
            djRFWW9GSW5Ib253aU9RcFpNRzM0NlkKIDkmFRbb9UiABCyu6XOLrLenVkgRd+la
            fINnWPtcBpWKQT80C84MMs5p6FDh6ShFFc0R2sgiEQth1XJk81TSbQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dj7a33nw06fg635y54t2x97mjjvec2yulx2ne3e54xa79a3d59ws8g0lw9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSGxYR3lUcmJsYkI3ZGZN
            Z1lITFhHcThhaDFpKzR3Vlh0VWJRaGYxcGxZCk9HVUYwVnp0eW8waVpjZklzb3Uw
            bWRrbXlnWGJvV3owMU9TQ2hTWmRaSTgKLS0tIFNSdDRkNm9zTTVxeERVZDVVR3lX
            c1ZGeEU5dm0rVng0WDZ4RXpVQVNNWEUKMUcRQ//SAB9ZxcZM27zdh0pDBhkywTCL
            ECcAvfzIi5hOhrZ3r/SYWa865k7DfCeh6lOGEYki1d/Bjwn1kHF9qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T16:11:59Z"
    mac: ENC[AES256_GCM,data:U4nnPCTBzCtTUB4aX4P2+CCx3jXu+9inxHhWqXy9KgvUU5rb//lRmRSnPk9/Ro/nMNwlitUt4i7Ip46QpSEj6/fvq4dWhaNszrfAPAZ3/g6BbiRHdZ5YfNUssbtHBOfx189wif9xBRMB6y5k7cP3t3GsUTybgZTtRuW6UWS01lQ=,iv:yL3gGF8RYy75vVg0zWq8LG+MPRLKCQLqSTZXTYRKtag=,tag:X9SIBc8l+zssTep3P2gxpw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
