ssh_master_pem: ENC[AES256_GCM,data:VQyt3UGKNMPkAgSVuMJqpA/+ooNpM3p4Tml7+MzH/KMy95DnCIZ3v/IuOdYyuKbqfuSoHh51W7qtQkfcYyrVVojN4nUrjvayoLm++O455Zpzto/RcrRWMRVXSV3l6A7K1uIySdQWM2msWOW/uqMc2srXUyWPh1BRn17ZJ5RwX1lYwHyXd89azNQ3plcADJi2SAhAA3zv732DM1YT1qvNX0dbMMHGWKij7RyY9fFpeBYAfo6AsmuTM6rEOs69HH9jzBW+b8QwRgPrprDnWYrV0P6GvANpauincOkPdaFtNd5r5sR4FBp75mn3KqyjeAPVdHpJB6qj5GuAh//9t/ppatnVizwZWlIvrlSOPXZZm4xbL4VmzrTk4pbGFkw0I+XsXBQDZ9S6iLjEViZMdY9GpyUVJGB93zCfNeO8cvF63VkSHxbGdqVppwoIEZkY6kugUPQb7hjYwcuHbqdCu2r/Y53SVJWtLs68KR4nJU0pV67ZW1rjGP6uVKRMrTEiDlNFy9YZxrGS2f/UYoL3eyiZXGh59kZkVdj1YHs7,iv:6oIoNCpWCDH8DpHDU87bf4Vn/vrB/wUNr6viPJJ16sU=,tag:VjXvE5bhx0sSO5BsUDzpWg==,type:str]
ssh_master_pub: ENC[AES256_GCM,data:3Nyu7ffHNZQRF3bGfN8TmaqR0zsKVXkkqc0Wb0piobxrwzav0mF5mKgJDWexRZCBVPIdBtRtTCpMQmL5r2wqWVpg5OmzD5UTTm+pQZzJGOGi4PKNahgssCJbpqz02UxwYxjpIR2K,iv:So576zLqP2jv2HIpPfaIEbIUxbI4LReCIOfg5S2Cs3k=,tag:NMbwdr531aR4eH5dUd2kLg==,type:str]
tailscale_authkey: ENC[AES256_GCM,data:HF3C6QXvRzIv2DBy0q/qk3QXz7eSlAWPYUPavQJxkkYtksTN8F+JTYmAw13FJbEGWLCWbHVzehD53GytjHM=,iv:9YfRMnhI6LIhsQSIIx0RAL6JTZDN9h9aQa575FsUKjg=,tag:cGdGz0wnM15MCpIof0LfTQ==,type:str]
tailscale_sidecar_authkey: ENC[AES256_GCM,data:92VdrP0lE8qeAmVVgXv4N0D+4WO0lqFbUKsp6IxB7SShGFltWmX6LfhZvVOCdTMC/UazELV2XBlZX4PS0g==,iv:E/wC5oyEoIU2OkjWaGuQTaC4tT5GhLlnPWgG3zGorWE=,tag:TMunG3wZkA+4aULdoBOaFQ==,type:str]
cloudflare_caddy_api_token: ENC[AES256_GCM,data:ouGw71/Z74s11bCERo0rs4g02CDbrSxFDdwUpo/rbGbxQmZTEKTzRg==,iv:Q+8u8apRo6xfNRezTjQC3V2LZl0O5m+4LBBLfps/5tg=,tag:ORmYseTd2xwcxaueCCw3Uw==,type:str]
searx_secretkey: ENC[AES256_GCM,data:eZuSd4I2eL9M//Epw/YwAB17Bsf2IQ==,iv:CVGgjeHNHbF1pJTIA3VrnT3YRV2m/gozFYGLQMiJuJA=,tag:AEaBACrxN9oV9BJcAUgmCg==,type:str]
pihole_webpassword: ENC[AES256_GCM,data:eOJ7lVus,iv:RgolzhQ3DdIzNKJdqcpsOopeDyuTHDini32xIP8JmIw=,tag:5K9gtrlUXPj7Jh0dIzwX7g==,type:str]
tailscale_disablement_secret1: ENC[AES256_GCM,data:fFOx9HmJCHQgCjjoK/rL8pmSg/OFYT5bM3VWMVyOSsCPch6yO9JyMlYU70Vc130t0WLg8d/KwJUlgf+XQF4opg==,iv:I6xXTLw83RYeU1o1C++TI3KCU9KCZ01+aDElTA4YFqY=,tag:vBcnHab4t2A54RfohqCJ3Q==,type:str]
tailscale_disablement_secret2: ENC[AES256_GCM,data:YSPMwagNMVZl4KGC1b5mwPAuIutzYbCey5klJLl1sUEvvNypuRAl8lctUDzFkdkA7g9YeugtWU1lSqgs+bKT4w==,iv:SxmWAmnyxS0B/UrChqEymTyk1jyWFrE9e47TbfKllBM=,tag:az6AZ7KQJT55ByODaxUsjw==,type:str]
tailscale_disablement_secret3: ENC[AES256_GCM,data:WCnODpx5KvohuSCpGo7L/Ds7vbrqIVmRWEausJKJl+FegCrMWV18yvbDI57g1izEut7QFIrBKTz+htSnci7Wbw==,iv:9GdAWj6U07Itm/Wgrxzdzx53E3zzoJHZnXQsJiPpgpI=,tag:44OGH60qAATvzNVZH09dbA==,type:str]
tailscale_disablement_secret4: ENC[AES256_GCM,data:5vhJE3SNwt49dKKUR8yeLQkpj5qBjd0GZdyT67VcXq9J48jYIF0WSuTH+O79LVzzwwAZZ4/ditrfRKTGTAKslg==,iv:riseYUaQuFfYnErZl/VvsYVjqWGpnFhDQnP+4+WM6ao=,tag:iAzNgXVBlW+CVTR2ic/JAw==,type:str]
tailscale_disablement_secret5: ENC[AES256_GCM,data:W7Wa/LmWAk/7nk+rRrQuHkNVjEUQnSJ3U8WMHyih4CzQ4gAaV8fEal2xPfpMH4kV63eACkZ1if+I1TDDRBbFnA==,iv:BgXw1T1WPTNNa4iWCHZPg9IcdRrvUo9IU4Cj0lO0pwc=,tag:vupew/KCRsUEW1LMmBEHWA==,type:str]
tailscale_disablement_secret6: ENC[AES256_GCM,data:drroXLlaGN/DR+49pTQB6qlxkvNshCsDL1z52469EVlvLIZjeU2Qh5mOEk9UrKXp2fch9JmHbHNfsDY5cBt+gA==,iv:wdJyyPJXfRdFzoxGLRa4woUH1O8PYyML7iqxyPmOIlg=,tag:lQQacyJsq1TXxBHdwilWig==,type:str]
tailscale_disablement_secret7: ENC[AES256_GCM,data:GBCfFKmAlx9JX8tYkrfKlAa+vSdyB3lOx1Q9m/viZEv//9Isve4u+50oLI37yuPLuSBXPW3gjyc6OQubO/YOXw==,iv:Rh1B3WMIvLH0qPi5/hvSxGUxoO++WMC+MRAF7ZXfx8g=,tag:AY01/G+IRGI11vQyKtLJyg==,type:str]
tailscale_disablement_secret8: ENC[AES256_GCM,data:g4TehThAQjsACE20b+xXPZ5YfoD7MXb6IXeMEfrR99h41cn8GkSu3O8hd5zU+LaVKN1kFkU5zuBJVwmA3mD8ZA==,iv:kdiXpgKwTAKi3FvuR9eXF1RhrRq5qeliEjF+RNnliG4=,tag:szzg+VsAjyCO2qiKaS2TQw==,type:str]
tailscale_disablement_secret9: ENC[AES256_GCM,data:tM0Vt3O7FgjP1UYW/ZHV6yII6vM30gekHgKin/vYbaezAJY4ZvIsteu2XFT+4U0c16zO3bNLOAmAQI0MEuoYsg==,iv:jPsHCYqu7M1R5L5J37tOpg4T53md9HJIkt6BVZkntwI=,tag:2JnKfSz4uiqIegDzq9JxbQ==,type:str]
tailscale_disablement_secret10: ENC[AES256_GCM,data:+YYzqFbGfH5IB4H/ujvQqIEeyfsyphp1xxInmY5GCQpbGg+/cbo9TohqyRCeF41ZsQRryRxRa9ei6S2LQ3Gh2g==,iv:BrUraPKsJoIjvdlW3NLPB2R5P0/3yJXOw07jxqSP23k=,tag:sqqEoLvlC4p0np543Q8Lzg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16ckghl2xua7qgun5xvz7l4h9g4rd8u09azxndurv7x3en6qq74aqh55227
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVG9MZDBqOHdFTTZ5alBi
        LzVBRmNJeE9nckg4aGdNRTFSSm11Wk1LblVnCjNPZ3ZERkZ1SjdzMEswQm9xOEpj
        aTNITDFYNDRTRGZNbmFPKzZJT1I5OGcKLS0tIGZEYkh2TktiMDE0em5kWk40ZFNh
        S2FJOVpVNXlOTUpHazZHbFVUVy8ydTgKtz7bsEjmdDmxbDtEFDZ+W+xU3AAUVcNk
        oq61ioAJAK34IndDy1BEKTQytyp/CBn7tCthNfaB2MDOe3KqgNZmqA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age144yp573ar5t9ecealclv408mdnaskxp8xv8h96pn70frtx6lffjqmzt2du
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZFNOa3lxUGlLWVBvZU9E
        bHBVTGRrcW5PSGpidHhxVUNpTlhaNyt3N0V3Ck9lcktTaGF6Ym53WktDV041MUxl
        SXVXck9rL2plQ2I0L1BscnlhbVptbkkKLS0tIDlUalVibGgrOTZxUCtmbTU4bFJ0
        aE9wT0F5WTg2WnprVVFzRDNpMUFkUVkKwzPaYW5V82D2Y+RoCmRLiIPETZp1I7a2
        ISeLxDVTCEAB8uvWOIRYaj2tGTAURQOtnLTLezqsQAyO/5Cj7CcWng==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age19l0yr2d6jp5c5gnaf4tr2hlcvg6gpql0fy9llrm4dfd9rxd8m3rqnl0w7m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSzJYL1JSYi9tVWNMZXY3
        VUw1am85OHJEek1uY2ltcmJOSVRtTC80d1JNCktzQUpTemdLem54TDZFbmQ3YlRJ
        SEdxWlBRMFdIdzNVQ0xuU2hvcEV1QjQKLS0tIE1FaTJxRk5jU1J0QlJydzV3dmo5
        Z1o4K0NDaXpkanZlYStzSDhBMEx0TncKOUg0bPAAZd9rFWAtNBXN07gHkmQO+w5Z
        GwvCgc4SfCbsGPgOVAdCebuK5DlG7wFMdyzLjpJUSoJ+x66xZmg5tw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-08T23:08:35Z"
  mac: ENC[AES256_GCM,data:sicTHGGLqvPlUFJIgOCY845voCfeS2zg7HOWWTU08I3p0isPTzqNAYLgo9eXTTlrwwM/1KzGDoEU6cQ1bxsFAU9RpT8xNjeN35AjkrZZGevVUMUxYfJ0yHJzOglLDKXy3UdWfxA9UAcMJdqKj1NVmZLr/ZD/0ZcajiDyvNWBRx0=,iv:+9jAqzLZ4zux6ekFNp6N5dPwk0MDfhQcRy8pDcKtMtw=,tag:mqJHK2YSfXehifPcGFow/Q==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.2
