ssh_master_pem: ENC[AES256_GCM,data:VQyt3UGKNMPkAgSVuMJqpA/+ooNpM3p4Tml7+MzH/KMy95DnCIZ3v/IuOdYyuKbqfuSoHh51W7qtQkfcYyrVVojN4nUrjvayoLm++O455Zpzto/RcrRWMRVXSV3l6A7K1uIySdQWM2msWOW/uqMc2srXUyWPh1BRn17ZJ5RwX1lYwHyXd89azNQ3plcADJi2SAhAA3zv732DM1YT1qvNX0dbMMHGWKij7RyY9fFpeBYAfo6AsmuTM6rEOs69HH9jzBW+b8QwRgPrprDnWYrV0P6GvANpauincOkPdaFtNd5r5sR4FBp75mn3KqyjeAPVdHpJB6qj5GuAh//9t/ppatnVizwZWlIvrlSOPXZZm4xbL4VmzrTk4pbGFkw0I+XsXBQDZ9S6iLjEViZMdY9GpyUVJGB93zCfNeO8cvF63VkSHxbGdqVppwoIEZkY6kugUPQb7hjYwcuHbqdCu2r/Y53SVJWtLs68KR4nJU0pV67ZW1rjGP6uVKRMrTEiDlNFy9YZxrGS2f/UYoL3eyiZXGh59kZkVdj1YHs7,iv:6oIoNCpWCDH8DpHDU87bf4Vn/vrB/wUNr6viPJJ16sU=,tag:VjXvE5bhx0sSO5BsUDzpWg==,type:str]
ssh_master_pub: ENC[AES256_GCM,data:3Nyu7ffHNZQRF3bGfN8TmaqR0zsKVXkkqc0Wb0piobxrwzav0mF5mKgJDWexRZCBVPIdBtRtTCpMQmL5r2wqWVpg5OmzD5UTTm+pQZzJGOGi4PKNahgssCJbpqz02UxwYxjpIR2K,iv:So576zLqP2jv2HIpPfaIEbIUxbI4LReCIOfg5S2Cs3k=,tag:NMbwdr531aR4eH5dUd2kLg==,type:str]
tailscale_auth_key: ENC[AES256_GCM,data:l7G5ds2tGYo3OrvT+jXzCuVTdWp66piKpLXDYiYmHFWFK1wJ5IUSV4rRw65kk/el8Da/F52hO4wyQ29EMuY=,iv:Tqn60JpxZKJxxoAQhfkPbsGo+Oy20hvygLlLhy0/+9c=,tag:VONhgXutu2ur3H/95WvlBw==,type:str]
pihole_webpassword: ENC[AES256_GCM,data:eOJ7lVus,iv:RgolzhQ3DdIzNKJdqcpsOopeDyuTHDini32xIP8JmIw=,tag:5K9gtrlUXPj7Jh0dIzwX7g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16ckghl2xua7qgun5xvz7l4h9g4rd8u09azxndurv7x3en6qq74aqh55227
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUlM1cUVTR2NtYlZlWFZJ
        VjhEYmlYWk9aQlc2MTVlUnZWQ29BancrLzJRCkpPcFBMb2FwYVM0RWY4bUx0K0hQ
        MzhYclpKUUtvWVpsdExSMGhhTzJGZjAKLS0tIHpqWjlWVG85WmI5TmVSZHkrZDBp
        T3hvZkpMTDVMaUtnZzVNWStGZnBYSFEK8yq63Wb3KZqxRUvkNvEP0NHhSymoWq5e
        xF3Nszd2ThAnNf7TP0NwA5uQfHdmQrnNpDm5anUG+Hw9Vu1iLQQtVg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1dj7a33nw06fg635y54t2x97mjjvec2yulx2ne3e54xa79a3d59ws8g0lw9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZ2t5a29FY21MbWd5SHc4
        TWc0L29QSWp0R0JyMlJCVU1hd1p4TTcvS1RJCmhBTGwxaGRMTDArK05uRGg2WWtO
        bTVXMnlLOXVhR05ML1M1MUVEOTlDMG8KLS0tIFlsdUdkaGN5M3l6ZEZpb1ZvOFNi
        dmNYNU9tWFdhK3BSSFprZk1qdmxmSUEKDAapmOLa0ozfAqWY1pVZKWrzbHLdhVwp
        JlvhcPTDNjGoV3oaQpiXY3FAgVZIsSVhMexr7f7hOhYDpW8Dd0+J2A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age144yp573ar5t9ecealclv408mdnaskxp8xv8h96pn70frtx6lffjqmzt2du
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaFVJRlo4M3k5TjlvUjhl
        bEhIdzRoSDZKM2JFeXN6YkN5N2lOa2NaTml3CnJHOVlsRnBodlJpYlk0NnpQWWs0
        U2l6YTVySUZFQnVWSjZ2cHJ5Wit4MTQKLS0tIERQeE4wbEJBbDVITlJxbEIxTDVk
        S3QvQ3dFWGx4TXIwbU1XMGFMeHVPUVUKeHu/Q3Ymggy0//jSp2xVcOy3K55UshBR
        oBzyNJtJ1kFerOsUODem37A3eOi2w65u6t8bZIO34nmvlYFboJtmyA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age19l0yr2d6jp5c5gnaf4tr2hlcvg6gpql0fy9llrm4dfd9rxd8m3rqnl0w7m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cEZJamhpc2x5ZEdvd2RS
        V2JicFBiaVZmZmxlVG02azlDbGN5NGo4K1QwClFCeDRQZFZodjU1QWJCMVRxSUU0
        YVhsWUwyZzBkL0dvL2MrOVFicHhVLzAKLS0tIGtoeTN1YURkSTBhSzlseExiSitC
        Nmxwb1ZtbnUwdkI4Y1lmcllQYkJQNkEKlTMuNZ7hrF8BK2fOp7Ih/WIODtKZKRnT
        //g/yRzHrveqrIUReFzcUd+QTmti4OfaI+S0/+CY7BZhKwOlfoM1hw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-06T00:46:36Z"
  mac: ENC[AES256_GCM,data:vRRys2ULDrZk+t0NjN5KqajqKMciJ1oKuWdrWonUhu8BIG13qLkgmOwrXqpfQmBLRNtxHIxlxIbOpjzMsjAPCfpie6PSo+cqLNwOUXClqPVqvqKm8d9+Da4p09mSxeYR4rgPZcDu4dibjHy7jSsZIW/kHZDWgoxG3m8XKhFZddA=,iv:57+ixwFny9l8jtMowVbFEVMKWTA8hC6EmmnfyVYuCJ0=,tag:4/vIrBDiUndlGrQJ+5xQVg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.2
