ssh_master_pem: ENC[AES256_GCM,data:VQyt3UGKNMPkAgSVuMJqpA/+ooNpM3p4Tml7+MzH/KMy95DnCIZ3v/IuOdYyuKbqfuSoHh51W7qtQkfcYyrVVojN4nUrjvayoLm++O455Zpzto/RcrRWMRVXSV3l6A7K1uIySdQWM2msWOW/uqMc2srXUyWPh1BRn17ZJ5RwX1lYwHyXd89azNQ3plcADJi2SAhAA3zv732DM1YT1qvNX0dbMMHGWKij7RyY9fFpeBYAfo6AsmuTM6rEOs69HH9jzBW+b8QwRgPrprDnWYrV0P6GvANpauincOkPdaFtNd5r5sR4FBp75mn3KqyjeAPVdHpJB6qj5GuAh//9t/ppatnVizwZWlIvrlSOPXZZm4xbL4VmzrTk4pbGFkw0I+XsXBQDZ9S6iLjEViZMdY9GpyUVJGB93zCfNeO8cvF63VkSHxbGdqVppwoIEZkY6kugUPQb7hjYwcuHbqdCu2r/Y53SVJWtLs68KR4nJU0pV67ZW1rjGP6uVKRMrTEiDlNFy9YZxrGS2f/UYoL3eyiZXGh59kZkVdj1YHs7,iv:6oIoNCpWCDH8DpHDU87bf4Vn/vrB/wUNr6viPJJ16sU=,tag:VjXvE5bhx0sSO5BsUDzpWg==,type:str]
ssh_master_pub: ENC[AES256_GCM,data:3Nyu7ffHNZQRF3bGfN8TmaqR0zsKVXkkqc0Wb0piobxrwzav0mF5mKgJDWexRZCBVPIdBtRtTCpMQmL5r2wqWVpg5OmzD5UTTm+pQZzJGOGi4PKNahgssCJbpqz02UxwYxjpIR2K,iv:So576zLqP2jv2HIpPfaIEbIUxbI4LReCIOfg5S2Cs3k=,tag:NMbwdr531aR4eH5dUd2kLg==,type:str]
tailscale_auth_key: ENC[AES256_GCM,data:trGyyimbQnsA3kwInau8MUiwjOn3hKz13ZSPvSf4InVKMb0GV7C4NiedZVNC5SWa1LbUgrdKHxurf7SdyQ==,iv:GRblspWBbq2L6sxWUKR3ewPprBWBIsmHpq70T8SNZ5w=,tag:LbgeR6suPBt7j/TWuy4utg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16ckghl2xua7qgun5xvz7l4h9g4rd8u09azxndurv7x3en6qq74aqh55227
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXc2JPNjMvS2xnciswTGFW
        Mmc3WXQzcngxLzJaalNabzNjc3ZuVUw2b2tjCnhTaFdtcEJkQUdTQTZJTFR0T1p4
        aE03clU1aEllMlYzWm9QL09DbVdBQ0kKLS0tIDFTTlJucjlwR2xXWWFEUG1BdUZ5
        bHI0WjhNZnNaSVdsUW91TzNCRThJbFkKoYMyCl9KXG0vM9VXGODJpt0SODcaxm4o
        2mXoAGCL8XEax/9mZrjYO2c6hgPShTpf6mL2J1fTQx8P+HTNeFCwWg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1dj7a33nw06fg635y54t2x97mjjvec2yulx2ne3e54xa79a3d59ws8g0lw9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFM2hjelhBYXZnN0x5NmRD
        UGxqZk0raHMvUHdWblAwc25rTmJwbERVVlRVClFUTUZHaVFTNHA2cm1NR3Fsakh5
        dEFrVW5ZeWF0S3RLckZteGxJT0tOWU0KLS0tIGl3QUJlM0hCVHEvZTZmWDN0NFpJ
        L3F5SmRGYlZZSURmUE9QL1ZhOHdKTk0KhxvhwiOntRE+NYLun+TILKo+YaRL8M9f
        qt9eCIrjCnCX32ykb0ePRNMqNtj8YWTJRyXkWA/8Jgs01ewS1O+q2g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age144yp573ar5t9ecealclv408mdnaskxp8xv8h96pn70frtx6lffjqmzt2du
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZG9OWlFPUjZENHBaTE9y
        ZmwrM3VVdFByVSt3ZVhKZEJGTEpLSEdheXhRCjBOaGVaZk1aenFTeFZhZXhFYmlQ
        SWk5Q3NKOWJnOHN0YUZ2eDBwMlR2NUEKLS0tIGdDR0pyYXp3RFZMeVZMWUNxTVRs
        ZGxaMEVsd2FBcVpkMDJzRlphZ0dZRTQK3FfYYglhoSM58YWVFC9Dyrtxr1ilbZR9
        1IooMqKAoohwv7EssHsVhVi/L43ktY2Aw70MLebAQAqnYjk6MBM1Aw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-04T15:41:50Z"
  mac: ENC[AES256_GCM,data:iikVsBykexKdEhtk2V6dAPpN+6vfkVU8rYE+i/go0KHj48x3vOMergv9REva9gxiwUm+P6kFSr5mbUa3NwodfRdBzzpR8ZRUgkmkFlHhNkY+7KhF0s+N4u4v9n3/YpR7In6GDzCGruH/rWkX6BEtMWg8cakEiNrTrMAdL1UEzEo=,iv:bkyTdIKeE1QEfjOD/31MocX6HJyZjEA6mVGBkKWTYCc=,tag:y8OOk10lAv9ATdn6Lm1lZg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.2
